
name: heart-disease-env
channels:
  - defaults
  - conda-forge 

dependencies:
  - python=3.12 
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - pip
  - pip:
    - mlflow
    - dagshub
    - joblib
   
