name: CI Workflow Advanced (MLflow Project + Docker)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set up job
      run: echo "Starting job setup."

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.12.7
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies (Miniconda env)
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        python-version: 3.12
        auto-activate-base: false
        environment-file: MLProject/conda.yaml
        activate-environment: heart-disease-env

    - name: Run mlflow project
      shell: bash -l {0}
      run: |
        conda activate heart-disease-env
        cd MLProject
        mlflow run . -e main -P data_path=heart_clean.csv

    - name: Get latest MLflow run_id
      shell: bash -l {0}
      id: get_run_id
      run: |
        conda activate heart-disease-env
        cd MLProject
        if [ -d "mlruns/0" ]; then
          RUN_ID=$(ls mlruns/0 | grep -v meta.yaml | grep -v params.yaml | tail -n 1)
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT
        else
          echo "run_id=" >> $GITHUB_OUTPUT
          echo "mlruns/0 not found!"
        fi

    - name: Install Python dependencies (additional)
      shell: bash -l {0}
      run: |
        echo "Installing additional Python dependencies step (modify if needed)."

    - name: Debug MLflow Installation
      shell: bash -l {0}
      run: |
        conda activate heart-disease-env
        echo "MLflow version:"
        mlflow --version
        which mlflow
        mlflow --help

    - name: Build Docker Model
      shell: bash -l {0}
      run: |
        conda activate heart-disease-env
        # Gunakan RUN_ID dari langkah sebelumnya
        mlflow build-docker MLProject --model-uri "runs:/${{ steps.get_run_id.outputs.run_id }}/model" --image "lthfiwlndri/heart-disease-model"

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Tag Docker Image
      run: |
        # Sesuaikan nama image awal (lihat output mlflow build-docker)
        docker tag lthfiwlndri/heart-disease-model:latest lthfiwlndri/heart-disease-model:latest

    - name: Push Docker Image
      run: |
        docker push lthfiwlndri/heart-disease-model:latest

    - name: Complete job
      run: echo "Job completed successfully."
