name: Upload MLflow Model to Google Drive

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  upload-model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # (Optional) Setup conda environment, edit/remove as needed
    - name: Setup conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: environment.yml
        activate-environment: heart-disease-env

    # Install rclone
    - name: Install rclone
      run: |
        sudo apt-get update
        sudo apt-get install -y rclone

    # Setup rclone config from secret
    - name: Setup rclone config
      run: |
        mkdir -p ~/.config/rclone
        echo "${{ secrets.RCLONE_CONFIG }}" > ~/.config/rclone/rclone.conf

    # Upload ML model to Google Drive
    - name: Upload model folder to Google Drive
      run: |
        # Ganti path di bawah sesuai dengan folder/file yang ingin di-upload
        rclone copy ./mlruns/0/${{ github.run_id }}/model gdrive:mlflow-models/heart-disease/${{ github.run_id }} --drive-root-folder-id ${{ secrets.GDRIVE_FOLDER_ID }}
