name: MLflow + Docker CI/CD

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Setup Python (versi yang kamu sebut: 3.12.7)
    - name: Set up Python 3.12.7
      uses: actions/setup-python@v5
      with:
        python-version: "3.12.7"

    # 3. Check environment (contoh: print Python & pip version)
    - name: Check Env
      run: |
        python --version
        pip --version

    # 4. Install dependencies (dari requirements.txt)
    - name: Install dependencies
      run: pip install -r requirements.txt

    # 5. Run MLflow project (ganti dengan command project kamu)
    - name: Run MLflow project
      run: |
        python run_mlflow.py

    # 6. Get latest MLflow run_id (contoh: ambil run id terakhir dari mlruns/0)
    - name: Get latest MLflow run_id
      id: get_run_id
      run: |
        RUN_ID=$(ls -td mlruns/0/* | head -1 | xargs -n1 basename)
        echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT

    # 7. Install Python dependencies tambahan (kalau ada, bisa digabung step 4)
    - name: Install Python dependencies
      run: pip install rclone

    # 8. Install rclone CLI
    - name: Install rclone
      run: |
        sudo apt-get update
        sudo apt-get install -y rclone

    # 9. Setup rclone config dari secrets
    - name: Setup rclone config
      run: |
        mkdir -p ~/.config/rclone
        echo "${{ secrets.RCLONE_CONFIG }}" > ~/.config/rclone/rclone.conf

    # 10. Upload MLflow model folder ke Google Drive
    - name: Upload to Google Drive
      run: |
        rclone copy mlruns/0/${{ steps.get_run_id.outputs.run_id }}/model gdrive:mlflow-models/heart-disease/${{ steps.get_run_id.outputs.run_id }} --drive-root-folder-id ${{ secrets.GDRIVE_FOLDER_ID }}

    # 11. Build Docker image
    - name: Build Docker Model
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/heart-disease:${{ steps.get_run_id.outputs.run_id }} .

    # 12. Login to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 13. Tag Docker image
    - name: Tag Docker Image
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/heart-disease:${{ steps.get_run_id.outputs.run_id }} ${{ secrets.DOCKER_USERNAME }}/heart-disease:latest

    # 14. Push Docker image
    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/heart-disease:${{ steps.get_run_id.outputs.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/heart-disease:latest
