name: CI Workflow Skilled (MLflow Project + GitHub Artifact Upload)

on:
  push:
    branches:
      - main
jobs:
  build-and-upload: 
    runs-on: ubuntu-latest 

    steps:
    - name: Set up job 
      run: echo "Starting job setup." 

    - name: Run actions/checkout@v3 
      uses: actions/checkout@v3 

    - name: Check Env
      uses: conda-incubator/setup-miniconda@v3
      with:
        conda-file: Workflow-CI/MLProject/conda.yaml
        architecture: x64
        activate-environment: heart-disease-env 
        cache-environment: true

    - name: Verify Env
      run: |
        # Check which Python interpreter is being used
        which python
        # Check installed packages
        conda list
        # Or pip list if you installed via pip
        # pip list

    - name: Set up Python 3.12.7 
      uses: actions/setup-python@v4 
      with:
        python-version: '3.12' 

    - name: Install dependencies
      uses: conda-incubator/setup-miniconda@v2 
      with:
        miniconda-version: "latest"
        python-version: 3.12 
        auto-activate-base: false
        activate-environment: heart-disease-env 
        environment-file: MLProject/conda.yaml 

    - name: Install MLflow (basic) 
      shell: bash -l {0}
      run: |
        echo "Installing mlflow using pip..."
        conda activate heart-disease-env # Aktifkan environment
        # Cukup instal mlflow dasar jika tidak perlu build-docker
        # Atau biarkan mlflow[docker] jika di conda.yaml
        pip install mlflow --upgrade # Atau sesuaikan jika di conda.yaml pakai [docker]
        echo "mlflow installation complete."

    - name: Set up MLflow Tracking URI (Optional - for remote tracking like DagsHub) 
      shell: bash -l {0}
      run: |
        echo "Setting up MLflow Tracking URI (Optional - remove if using local tracking)..."
        conda activate heart-disease-env
        # Menggunakan nama secrets sesuai dengan yang Anda miliki (untuk DagsHub)
        echo "MLFLOW_TRACKING_URI=${{ secrets.MLFLOW_TRACKING_URI }}" >> $GITHUB_ENV # Hapus atau sesuaikan jika tidak pakai DagsHub
        echo "DAGSHUB_USER=${{ secrets.DAGSHUB_USER }}" >> $GITHUB_ENV # Hapus jika tidak pakai DagsHub
        echo "DAGSHUB_TOKEN=${{ secrets.DAGSHUB_PASSWORD }}" >> $GITHUB_ENV # Menggunakan DAGSHUB_PASSWORD (pastikan isinya token DagsHub), Hapus jika tidak pakai DagsHub
        echo "MLflow Tracking URI set."


    - name: Run mlflow project 
      shell: bash -l {0} 
      run: |
        echo "Running MLflow project..."
        # Konfigurasi MLflow Tracking
        export MLFLOW_TRACKING_URI="./mlruns" # Mengatur tracking lokal
        echo "MLFLOW_TRACKING_URI set to: ${MLFLOW_TRACKING_URI}"

        # Mengaktifkan environment dan menjalankan mlflow run
        conda activate heart-disease-env
        cd MLProject # Path yang benar relatif dari root repo
        # --- UBAH PARAMETER DATA_PATH DI SINI ---
        mlflow run . -e main -P data_path=namadataset_preprocessing/heart_clean.csv # <--- PATH DATASET YANG BENAR
        
    - name: Install Python dependencies 
      shell: bash -l {0} 
      run: |
        echo "Installing additional Python dependencies step (modify if needed)."
        # Contoh: conda activate heart-disease-env && pip install nama_library_tambahan


    - name: Upload to Github Artifact 
      uses: actions/upload-artifact@v4 

      with:
        name: mlflow-run-artifacts
        path: MLProject/mlruns/
        retention-days: 7 

    - name: Post Log in to Docker Hub 
      run: echo "Post Login handled by action." 

    - name: Post Set up Python 3.12.7 
      run: echo "Post Python setup handled by action." 

    - name: Post Run actions/checkout@v3
      run: echo "Post Checkout handled by action." 

    - name: Complete job 
      run: echo "Job completed successfully."
